# Generated by Django 2.1.5 on 2019-02-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190210_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='class_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
