# Generated by Django 2.1.5 on 2019-02-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190210_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_code',
            field=models.IntegerField(default=100, unique=True),
        ),
    ]
